version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/findclothes_deploy
hooks:
  BeforeInstall:
    - location: /before-deploy.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /after-deploy.sh
      timeout: 300
      runas: root
